### ISSUE TITLE
The use statement with non-compound name 'Exception' has no effect

### ISSUE THREAD

**Issue by YOzaz** [ramonk2o/simple-scraper-deprecated#7]
When used with composer, error message is thrown:

```
[ErrorException]
The use statement with non-compound name 'Exception' has no effect.
```

You should not import **Exception** class at the top of _SimpleScrapper.class.php_, as your class is not namespaced.
Just remove `use \Exception;` line completely and you'll be fine.

Additionally, you may consider adding autoload in _composer.json_:

``` json
"autoload": {
  "files": [ "SimpleScraper.class.php" ]
}
```

**Comment by ramonztro** [comment]
Import removed!
